{"total": 6217,
 "page": 1,
 "crunchbase_url": "http://www.crunchbase.com/search?query=facebook",
 "results":
  [{"name": "Facebook",
    "category_code": "social",
    "description": "Social network",
    "permalink": "facebook",
    "crunchbase_url": "http://www.crunchbase.com/company/facebook",
    "homepage_url": "http://facebook.com",
    "namespace": "company",
    "overview": "Facebook is the world's largest social network, with over [1.15 billion monthly active users](http://techcrunch.com/2013/07/24/facebook-growth-2/).\r\n\r\nFacebook was founded by [Mark Zuckerberg](http://www.crunchbase.com/person/mark-zuckerberg) in February 2004, initially as an exclusive network for Harvard students. It was a huge hit: in 2 weeks, half of the schools in the Boston area began demanding a Facebook network. Zuckerberg immediately recruited his friends [Dustin Moskovitz](http://www.crunchbase.com/person/dustin-moskovitz), [Chris Hughes](/person/chris-hughes), and [Eduardo Saverin](/person/eduardo-saverin) to help build Facebook, and within four months, Facebook added 30 more college networks. \r\n\r\nThe original idea for the term Facebook came from Zuckerberg's high school (Phillips Exeter Academy). The Exeter Face Book was passed around to every student as a way for students to get to know their classmates for the following year. It was a physical paper book until Zuckerberg brought it to the internet.\r\n\r\nWith this success, Zuckerberg, Moskowitz and Hughes moved out to [Palo Alto](/maps/city/Palo%2520Alto) for the summer and rented a sublet. A few weeks later, Zuckerberg ran into the former cofounder of [Napster](/company/napster), [Sean Parker](/person/sean-parker). Parker soon moved in to Zuckerberg's apartment and they began working together.  Parker provided the introduction to their first investor, [Peter Thiel](/person/peter-thiel), cofounder of [PayPal](/company/paypal) and managing partner of [The Founders Fund](http://www.crunchbase.com/financial-organization/founders-fund). Thiel invested $500,000 into Facebook. \r\n\r\nWith millions more users, [Friendster](/company/friendster) [attempted](http://www.techcrunch.com/2006/12/12/yahoos-project-fraternity-docs-leaked/) to acquire the company for $10 million in mid 2004. Facebook turned down the offer and subsequently received $12.7 million in funding from [Accel Partners](http://www.crunchbase.com/financial-organization/accel-partners), at a valuation of [around $100 million](http://www.techcrunch.com/2005/09/07/85-of-college-students-use-facebook/). Facebook continued to grow, opening up to high school students in September 2005 and adding an immensely popular photo sharing feature the next month. The next spring, Facebook received $25 million in funding from [Greylock Partners](http://www.crunchbase.com/financial-organization/greylock) and [Meritech Capital](http://www.crunchbase.com/financial-organization/meritech-capital-partners), as well as previous investors Accel Partners and Peter Thiel. The pre-money valuation for this deal was about $525 million. Facebook subsequently [opened](http://www.techcrunch.com/2006/04/26/facebook-goes-beyond-college-high-school-markets/) up to work networks, eventually amassing over 20,000 work networks. Finally in September 2006, Facebook [opened](http://www.techcrunch.com/2006/09/26/facebook-just-launched-open-registrations/) to anyone with an email address. \r\n \r\nIn the summer of 2006, [Yahoo](/company/yahoo) [attempted to acquire](http://www.techcrunch.com/2006/09/21/facebook-and-yahoo-in-acquisition-talks-for-1-billion/) the company for $1 billion dollars. [Reports](http://www.wired.com/techbiz/startups/news/2007/09/ff_facebook) actually indicated that Zuckerberg made a verbal agreement to sell Facebook to Yahoo. A few days later when Yahoo's stock price took a dive, the offer was lowered to $800 million and Zuckerberg walked away from the deal.  Yahoo later [offered](http://www.techcrunch.com/2006/12/12/yahoos-project-fraternity-docs-leaked/) $1 billion again, this time Zuckerberg turned Yahoo down and earned instant notoriety as the \"kid\" who turned down a billion. This was not the first time Zuckerberg turned down an acquisition offer; [Viacom](/company/viacom) had previously [unsuccessfully](http://www.techcrunch.com/2006/03/28/facebook-is-doing-the-skype-dance/) attempted to acquire the company for $750 million in March 2006. \r\n\r\nNot long after, in October 2007, [Microsoft invested](http://www.techcrunch.com/2007/10/24/facebook-takes-the-microsoft-money-and-runs/) $240 million into Facebook for 1.6 percent of the company in. This meant a valuation of over $15 billion, making Facebook the [5th most valuable US Internet company](http://www.techcrunch.com/2007/10/25/perspective-facebook-is-now-5th-most-valuable-us-internet-company/), yet with only $150 million in annual revenue. Many explained Microsoft's decision as being solely driven by the desire to outbid Google.\r\n\r\nFacebook continued to receive funding, most notably in January 2011 receiving a [$1.5 billion round](http://techcrunch.com/2011/01/21/facebook-raises-1-5-billion-at-50-billion-valuation/), valuing the company at $50 billion. A year later, in February 2012, Facebook [announced](http://techcrunch.com/2012/02/01/facebook-files-for-5-billion-ipo/) that it was filing for its long-anticipated initial public offering. The company went public on May 18, 2012, opening on the NASDAQ with shares trading at [$42.05](http://techcrunch.com/2012/05/18/facebook-share-open-10-5-higher-at-42/).\r\n\r\nOne sour note for Facebook has been the [controversy](http://www.techcrunch.com/2007/07/16/the-ghost-of-zuckerbergs-past-may-haunt-facebook-ipo/) with social network ConnectU. The founders of ConnectU, former classmates of Mark Zuckerberg at Harvard, allege that Zuckerberg stole their original source code for Facebook. The ordeal has [gone to court](http://www.techcrunch.com/2007/10/10/facebook-vs-connectu-facebook-makes-untrue-assertions-claims-connectu/), and has now been [resolved](http://techcrunch.com/2011/06/22/after-seven-years-the-winklevosses-give-up-on-battle-with-facebook/). \r\n\r\nNotwithstanding this lingering controversy, Facebook's growth has been staggering. Facebook announced [astonishing numbers](http://techcrunch.com/2012/02/01/facebooks-s-1-845-million-users-every-month-more-than-half-daily-and-nearly-half-mobile/) in February 2012 upon filing for its IPO. As of July 2013, over [1.15 billion](http://techcrunch.com/2013/07/24/facebook-growth-2/) users log into Facebook every month, and 669 million users log in daily. Mobile users now make up half of Facebook's user base, with 819 million monthly actives. Facebook has also announced that by the end of 2011 there had been 100 billion friend connections, and in recent months users had been registering 2.7 billion Likes and Comments per day. Facebook is one of the [most trafficked sites](http://techcrunch.com/2010/12/29/hitwise-facebook-overtakes-google-to-become-most-visited-website-in-2010/) in the US, and its international growth has been impressive. Additionally, Facebook is the top photo sharing site with 250 million photos uploaded per day.\r\n\r\nFacebook users' [passion](http://www.techcrunch.com/2007/11/13/i-just-cant-be-a-college-student-without-facebook/)\u2014or [addiction](http://www.techcrunch.com/2007/03/09/career-advice-dont-choose-facebook-over-your-job/)\u2014to the site is unparalleled: more than half use the product every single day and users spend an average of 19 minutes a day on Facebook. The site's popularity has garnered it pop culture fame, so much so that in 2010 a feature film entitled _The Social Network_ was released which chronicled Facebook's inception.\r\n\r\nIn its 2012 [IPO filing](http://techcrunch.com/2012/02/01/facebook-files-for-5-billion-ipo/), Facebook announced that it intends to grow in the near future by expanding its global user base, increasing engagement by developing new social tools, improving the mobile experience, and creating more value for advertisers and users.",
    "image":
     {"available_sizes":
       [[[150,
          61],
         "assets/images/resized/0000/4561/4561v1-max-150x150.png"],
        [[245,
          100],
         "assets/images/resized/0000/4561/4561v1-max-250x250.png"],
        [[245,
          100],
         "assets/images/resized/0000/4561/4561v1-max-450x450.png"]],
      "attribution": null},
    "offices":
     [{"description": "Headquarters",
       "address1": "1601 Willow Road",
       "address2": "",
       "zip_code": "94025",
       "city": "Menlo Park",
       "state_code": "CA",
       "country_code": "USA",
       "latitude": 37.41605,
       "longitude": -122.151801},
      {"description": "Europe HQ",
       "address1": "",
       "address2": "",
       "zip_code": "",
       "city": "Dublin",
       "state_code": null,
       "country_code": "IRL",
       "latitude": 53.344104,
       "longitude": -6.267494},
      {"description": "New York",
       "address1": "340 Madison Ave",
       "address2": "",
       "zip_code": "10017",
       "city": "New York",
       "state_code": "NY",
       "country_code": "USA",
       "latitude": 40.7557162,
       "longitude": -73.9792469}]},
   {"name": "Facebook Genie",
    "category_code": "software",
    "description": "Facebook Application Development",
    "permalink": "facebook-genie",
    "crunchbase_url": "http://www.crunchbase.com/company/facebook-genie",
    "homepage_url": "http://www.facebookgenie.com",
    "namespace": "company",
    "overview": "Facebook is a social utility that offers an efficient way for people to stay connected with their friends and the people around them. Facebook users communicate and share information through the social graph, the network of connections and relationships between people. With more than 24 million active users, Facebook is the sixth-most trafficked website in the United States.\r\n\r\nFacebookgenie provides you a range of services which would includes:\r\n\r\n* Facebook application development.\r\n* Innovative and unique design layouts for your application.\r\n* Listing of the application in facebook application directory.\r\n* Developing marketing strategies and plans.\r\n* Market the application to a number of users worldwide.\r\n* Tracking your application.\r\n\r\nThe pricing model behind FacebookGenie includes a low one time development cost. FacebookGenie.com continues to tailor services to help a starving market of facebook application development. The opportunity of FacebookGenie is that anyone can realize the advantages of including a robust social networking platforms in their marketing campaigns without huge upfront costs. ",
    "image":
     {"available_sizes":
       [[[150,
          43],
         "assets/images/resized/0005/3953/53953v2-max-150x150.jpg"],
        [[250,
          73],
         "assets/images/resized/0005/3953/53953v2-max-250x250.jpg"],
        [[341,
          100],
         "assets/images/resized/0005/3953/53953v2-max-450x450.jpg"]],
      "attribution": null},
    "offices":
     []},
   {"name": "Facebook Search",
    "category_code": "search",
    "description": "Facebook Search Engine",
    "permalink": "facebook-search",
    "crunchbase_url": "http://www.crunchbase.com/company/facebook-search",
    "homepage_url": "http://www.fbsearch.us",
    "namespace": "company",
    "overview": "Facebook Search is a search tool for the Facebook social network. \r\n\r\nIt is powered by the Facebook Open Graph API and returns data that is publicly available. Users can search across posts, photos, people, pages, groups and events without the need to login or have a Facebook account.\r\n\r\nThe service features a way to search for images, photos and graphics from the millions of 'Pages' that form part of the Facebook social network. Users are able to find photos and images that have been hand curated by Facebook users.",
    "image":
     {"available_sizes":
       [[[150,
          70],
         "assets/images/resized/0011/0177/110177v2-max-150x150.jpg"],
        [[215,
          101],
         "assets/images/resized/0011/0177/110177v2-max-250x250.jpg"],
        [[215,
          101],
         "assets/images/resized/0011/0177/110177v2-max-450x450.jpg"]],
      "attribution": null},
    "offices":
     []},
   {"name": "Facebook Social Chatroulette",
    "category_code": "software",
    "description": "Facebook Social Chatroulette",
    "permalink": "facebook-social-chat-roulette",
    "crunchbase_url": "http://www.crunchbase.com/company/facebook-social-chat-roulette",
    "homepage_url": "http://www.fbchatroulette.net",
    "namespace": "company",
    "overview": "Facebook Social Chatroulette enables you to chat with Facebook users from all over the world.\r\n\r\nEarn badges for being a good chat partner. \r\n\r\nCollect flags as you visit different part of the world. \r\n\r\nOr just meet interesting people. \r\n\r\nOr make new Facebook friend.\r\n\r\n**Source(s):**\r\n\r\nWeb Site: [http://www.fbchatroulette.net]\r\nBlog: [http://fbchatroulette.tumblr.com]\r\nTwitter: [http://twitter.com/fbchatroulette]\r\nFacebook: [http://tinyurl.com/fbchatroulette]\r\nFeedback: [http://fbchatroulette.uservoice.com]",
    "image":
     {"available_sizes":
       [[[64,
          48],
         "assets/images/resized/0008/6458/86458v2-max-150x150.png"],
        [[64,
          48],
         "assets/images/resized/0008/6458/86458v2-max-250x250.png"],
        [[64,
          48],
         "assets/images/resized/0008/6458/86458v2-max-450x450.png"]],
      "attribution": null},
    "offices":
     []},
   {"name": "Trustship and Facebook Templates",
    "category_code": "ecommerce",
    "description": "Trustship Template Developement",
    "permalink": "facebook-templates",
    "crunchbase_url": "http://www.crunchbase.com/company/facebook-templates",
    "homepage_url": "http://facebook-templates.net",
    "namespace": "company",
    "overview": "Facebook  became a huge part of the online live. People are using it twice as often as Google and it counts over 500 millions active users surfing the pages of Facebook each day. \r\n Facebook advertising knowns as the most powerful solution in internet marketing and gives you the highest conversions  rates ever.\r\n Facebook-templates.net provides new product that helps internet marketers  engage and interact with FaceBook page fans and customers. \r\nwe also provide  Templates for Trustship (the new social network).\r\nConvert your Trustship profile traffic intro profit.",
    "image":
     {"available_sizes":
       [[[150,
          70],
         "assets/images/resized/0009/4583/94583v2-max-150x150.jpg"],
        [[181,
          85],
         "assets/images/resized/0009/4583/94583v2-max-250x250.jpg"],
        [[181,
          85],
         "assets/images/resized/0009/4583/94583v2-max-450x450.jpg"]],
      "attribution": null},
    "offices":
     []},
   {"name": "Facebook Templates",
    "category_code": "ecommerce",
    "description": "Facebook Templates online store",
    "permalink": "facebook-templates-2",
    "crunchbase_url": "http://www.crunchbase.com/company/facebook-templates-2",
    "homepage_url": "http://fanpagetemplates.org",
    "namespace": "company",
    "overview": "Facebook Templates is an awesome way to create a unique stylish custom facebook page for your business. While most of the businesses are landing they potential fans to their Wall, you can take advantage of professional facebook templates, designed with one only puprose - get you more fans.\r\n\r\nWe sell facebook templates in packs and for a very cheap price.",
    "image": null,
    "offices":
     []},
   {"name": "fforward.co - Facebook Analysis",
    "category_code": "other",
    "description": "Facebook analysis blog",
    "permalink": "fforward-co-facebook-analysis",
    "crunchbase_url": "http://www.crunchbase.com/company/fforward-co-facebook-analysis",
    "homepage_url": "http://fforward.co",
    "namespace": "company",
    "overview": "fforward, a Facebook analysis blog, explores financial, usage and growth, quantitative, and technical indicators to evaluate Facebook and its stock performance, and to explore trends in mobile computing. \r\n\r\nfforward has been cited by All Things D (WSJ), BuzzFeed, Quartz, and other publications. ",
    "image": null,
    "offices":
     []},
   {"name": "Facebook 'Like' Button",
    "permalink": "facebook-like-button",
    "crunchbase_url": "http://www.crunchbase.com/product/facebook-like-button",
    "homepage_url": "http://www.mageplace.com/facebook/facebook-like-button.html",
    "namespace": "product",
    "overview": "When user clicks the Facebook Like button it will automatically place the main product/category image and product/category name on the user\u2019s Facebook wall but also will provide them with ability to add comment to the record. Button can be placed on any pages of Magento store \u2013 product pages, CMS pages, category pages or Home page. \r\n\r\n\u2013 Supports HTML5, iFrame and XFBML buttons;\r\n\u2013 Box and button with count of likes as well as standard layout;\r\n- Ability to show profile images of Facebook users;\r\n- Ability to adjust the button to your custom design (button color scheme, font, height/ width and custom verb to display);\r\n- Indicate app id or admin id and track the button usage on Facebook;\r\n- Fast installation and set up of the extension with default settings.\r\n\r\nMagento Facebook Like button comes with Facebook Send Button. Using this button Facebook users can send message to their friend directly from your Magento store page: this message will contain link to your page and product. \r\n\r\nThe MagePlace Facebook Like Button supports Magento Community and Enterprise editions.",
    "image":
     {"available_sizes":
       [[[120,
          150],
         "assets/images/resized/0033/5817/335817v2-max-150x150.jpg"],
        [[200,
          250],
         "assets/images/resized/0033/5817/335817v2-max-250x250.jpg"],
        [[200,
          250],
         "assets/images/resized/0033/5817/335817v2-max-450x450.jpg"]],
      "attribution": null}},
   {"name": "Facebook Integration Bundle",
    "permalink": "facebook-integration-bundle",
    "crunchbase_url": "http://www.crunchbase.com/product/facebook-integration-bundle",
    "homepage_url": "http://www.mageplace.com",
    "namespace": "product",
    "overview": "Facebook Integration Bundle is a collection of Magento extensions adding Magento \u2013 Facebook integration to your e-commerce site. This all-in-one solution will let you add Facebook features to your site with one simple installation: Facebook Like button, Facebook Send button, Facebook Share button, Facebook Comments and Facebook Connect.\r\n\r\nFacebook Like button - your visitors will help you promote your store clicking Like button on Magento store pages. The extension will automatically place the main product image and product name on the user\u2019s Facebook wall. \r\n\r\nFacebook Comments allows visitors to make comments on your shop from Facebook accounts, placing record to the Facebook wall of the commenting person and involving their friends into discussion process.\r\n\r\nFacebook Connect \u2013 provide full Magento - Facebook integration and users' one click registration and login to Magento site with their Facebook profile. \r\n\r\nWith Facebook Integration Bundle you can save time and money by taking advantage of bulk installation of all features and one solution provider that provides qualified support, extension personalization and customization services.\r\n\r\nThe Facebook Bundle extension supports Magento Community and Enterprise editions.",
    "image":
     {"available_sizes":
       [[[150,
          150],
         "assets/images/resized/0032/3346/323346v2-max-150x150.png"],
        [[250,
          250],
         "assets/images/resized/0032/3346/323346v2-max-250x250.png"],
        [[250,
          250],
         "assets/images/resized/0032/3346/323346v2-max-450x450.png"]],
      "attribution": null}},
   {"name": "Facebook Connector",
    "permalink": "facebook-connector",
    "crunchbase_url": "http://www.crunchbase.com/product/facebook-connector",
    "homepage_url": "http://www.mageplace.com",
    "namespace": "product",
    "overview": "Facebook Connector Magento extension enables customers\u2019 one click registration and login in Magento with their Facebook profile. This extension takes customer\u2019s information from Facebook account directly into Magento and creates Magento account for this user. This way you save customers\u2019 time because they don\u2019t need to fill in all the obligatory fields. They need just to click the Facebook connect button, confirm notification from Facebook and can do shopping right away!\r\n\r\nFacebook Connector extension for Magento allows user to post updates on his wall about each purchase \u2013 this will bring you even more customers. Using privacy settings for customers in their profile in the Magento store customers can choose whether they want their purchases to be posted to the wall or not.\r\n\r\nThe MagePlace Facebook Connector will add Facebook Connect button to log in page and to checkout page.\r\n\r\n- Create Magento account automatically;\r\n- Customers\u2019 purchases can be posted to their walls;\r\n- Existing Magento account can log in with Facebook account;\r\n- Privacy settings for user;\r\n- Easy localization and customization with language file etc.;\r\n\r\nThe Facebook Connector extension supports Magento Community and Enterprise editions.",
    "image":
     {"available_sizes":
       [[[150,
          150],
         "assets/images/resized/0032/3331/323331v2-max-150x150.png"],
        [[250,
          250],
         "assets/images/resized/0032/3331/323331v2-max-250x250.png"],
        [[250,
          250],
         "assets/images/resized/0032/3331/323331v2-max-450x450.png"]],
      "attribution": null}}]}
