{"total": 371,
 "page": 1,
 "crunchbase_url": "http://www.crunchbase.com/search?query=instagram",
 "results":
  [{"name": "Instagraming",
    "category_code": "web",
    "description": "Meeting point for fans instagram ",
    "permalink": "instagraming",
    "crunchbase_url": "http://www.crunchbase.com/company/instagraming",
    "homepage_url": "http://www.instagraming.com",
    "namespace": "company",
    "overview": "Instagraming offers people all related to the world and all its accessories Instagram so one do not miss any new news. They also offer a range of exclusive products Instagram Instagram pesonas ideal for that start or already using Instagram.",
    "image":
     {"available_sizes":
       [[[150,
          29],
         "assets/images/resized/0038/1083/381083v1-max-150x150.png"],
        [[250,
          49],
         "assets/images/resized/0038/1083/381083v1-max-250x250.png"],
        [[300,
          59],
         "assets/images/resized/0038/1083/381083v1-max-450x450.png"]],
      "attribution": null},
    "offices":
     [{"description": "HQ",
       "address1": "Calle Julio Atienza Berrocal",
       "address2": "Collado Villalba",
       "zip_code": "",
       "city": "",
       "state_code": null,
       "country_code": "ESP",
       "latitude": null,
       "longitude": null}]},
   {"name": "Instagram",
    "category_code": "photo_video",
    "description": "Fast beautiful photo sharing",
    "permalink": "instagram",
    "crunchbase_url": "http://www.crunchbase.com/company/instagram",
    "homepage_url": "http://instagram.com",
    "namespace": "company",
    "overview": "Instagram is a free photo sharing application that allows users to take photos, apply a filter, and share it on the service or a variety of other social networking services, including [Facebook](/company/facebook), [Twitter](/company/twitter), [Foursquare](/company/foursquare), [Tumblr](/company/tumblr), [Flickr](/company/flickr), and [Posterous](/company/posterous). The application is compatible with iPhone, iPad or iPod Touch or Android devices running Android.\r\n\r\nIn an homage to both the Kodak Instamatic and Polaroid cameras, Instagram confines photos into a square shape. This is in contrast to the 3:2 aspect ratio normally used by the iOS device cameras.\r\n\r\nThe application was developed by [Kevin Systrom](/person/kevin-systrom) and [Mike Krieger](/person/mike-krieger).\r\n\r\nIn April 2012, Instagram was acquired by [Facebook](/company/facebook).",
    "image":
     {"available_sizes":
       [[[150,
          150],
         "assets/images/resized/0021/1498/211498v1-max-150x150.png"],
        [[250,
          250],
         "assets/images/resized/0021/1498/211498v1-max-250x250.png"],
        [[250,
          250],
         "assets/images/resized/0021/1498/211498v1-max-450x450.png"]],
      "attribution": null},
    "offices":
     [{"description": "Instagram",
       "address1": "P.O. Box 77421",
       "address2": "",
       "zip_code": "94107",
       "city": "San Francisco",
       "state_code": "CA",
       "country_code": "USA",
       "latitude": null,
       "longitude": null}]},
   {"name": "Improve Followers on Facebook | Instagram | Twitter",
    "category_code": "social",
    "description": "Internet Marketing",
    "permalink": "improve-followers",
    "crunchbase_url": "http://www.crunchbase.com/company/improve-followers",
    "homepage_url": "http://www.followerincrease.com",
    "namespace": "company",
    "overview": "Offering services designed to increase Instagram followers, gain Facebook followers, and boost your followers on Twitter. We offer promotion on Soundcloud in order to boost Soundcloud plays and help you gain followers. We can also provide Reverbnation users and musicians alike an increase in Reverbnation song plays in order to help you achieve a #1 local rank. Many users today wonder how to increase Pinterest followers, boost Pinterest repins, increase YouTube subscribers, gain more YouTube views but have noticed that with regular means of promotion this is proven to be quite time consuming and cumbersome. Our team of professionals are the best in our field providing countless Social Media services and benefits for those looking to increase followers, build their online presence, and increase exposure. We are the pro's simply because we treat your business and your campaign as if it were ours handling each account uniquely and professionally in order to achieve more than satisfying results. Try us today and watch your brand popularity soar!\r\n\r\nFollower Increase is the leader in innovation for social media marketing offering our clients low-cost but high quality promotion in order to garner new followers, achieve a greater online presence, and boost their overall online credibility.In the past six months social media has changed not only the way users keep in contact but also how businesses interact with potential customers. Social Media has become a new tool for organic advertising leading to increased sales and web presence.\r\n\r\nWith social networking expanding greatly users have begun clamoring for increased followers on their networks in order to garner web credibility. If you have heard about Social Media Optimization then you are aware of the benefits a strong social media campaign. Increasing your followers is perhaps the single most important aspect when developing your online presence. Follower Increase specializes in social media services and internet marketing giving our clients the tools they need in order to increase their followers and ultimately boost their social reach and online presence on top social networks.  \r\n\r\nFollower Increase hosts a group of dedicated professionals who specializes in social media marketing assisting our clients with their promotional campaign needs. We supply a variety of services including but not limited to: Twitter, Facebook, Instagram, YouTube, Web Design, Pinterest, Search Engine Optimization, Linkedin, and more. We offer special packages and services designed to increase your followers, gain Twitter followers, promote a YouTube video campaign, gain new Facebook fans and page likes organically. We offer Real followers and organic promotion is the key to a successful social media campaign for your business, product, or fan page.\r\n\r\nFollower Increase is home to the #1 site voted by clients, users, and businesses worldwide for quality social-media services, packages and consulting. We treat your business as if it were our business. Visit us at anytimes via www.followerincrease.com\r\n",
    "image":
     {"available_sizes":
       [[[150,
          149],
         "assets/images/resized/0031/0594/310594v5-max-150x150.jpg"],
        [[250,
          249],
         "assets/images/resized/0031/0594/310594v5-max-250x250.jpg"],
        [[347,
          346],
         "assets/images/resized/0031/0594/310594v5-max-450x450.jpg"]],
      "attribution": null},
    "offices":
     []},
   {"name": "Magento Web To Print: Instagram Photos Extension",
    "permalink": "magento-web-to-print-instagram-photos-extension",
    "crunchbase_url": "http://www.crunchbase.com/product/magento-web-to-print-instagram-photos-extension",
    "homepage_url": null,
    "namespace": "product",
    "overview": "**Why do you require this extension:**\r\n[Magento Web To Print: Instagram Photos Extension](http://magento.ikantam.com/store/web-print-instagram-photos.html) is going to equip any print shop with Instagram easy and convenient web-to-print functionality. \r\nNowadays, when the mobile devices are widespread as never before, Instagram is getting popularity in a flash. Owned by Facebook, Instagram earns additional points as developing social network, more and more people use it to share their images. Thereby, a print shop have no other choice, but to integrate this smart solution which will bring new customers with no significant efforts made.\r\n\r\n**How it works:**\r\nFor the store admin, there are several custom options available in the back-end such as possibility to add custom sizes for the prints, adjustable framing options, price fields as well as a few other minor options.\r\nOn the product page, customers just need to connect to Instagram via API, select an Istagram image to print, choose edge options, canvas size, and proceed to the checkout.\r\n\r\n**Features:**\r\n* Admin options to set the necessary values\r\n* User friendly interface to work with Instagram images\r\n* Instagram identification via API\r\n* localization option with the language pack\r\n* Easy and quick installation\r\n* 15 day money back GUARANTEE\r\n* Meets Magento programming best practices\r\n* 100% open source",
    "image":
     {"available_sizes":
       [[[150,
          150],
         "assets/images/resized/0023/9886/239886v2-max-150x150.png"],
        [[250,
          250],
         "assets/images/resized/0023/9886/239886v2-max-250x250.png"],
        [[285,
          285],
         "assets/images/resized/0023/9886/239886v2-max-450x450.png"]],
      "attribution": null}},
   {"name": "Magento Instagram Extension",
    "permalink": "magento-instagram-extension",
    "crunchbase_url": "http://www.crunchbase.com/product/magento-instagram-extension",
    "homepage_url": "http://www.ikantam.com",
    "namespace": "product",
    "overview": "[Free Magento Instagram Extension](http://magento.ikantam.com/store/free-instagram-magento-extension.html) adds an extra part of social integration for your store.\r\n\r\nThe extension is a good fit if you would like to integrate users sharing their experience of enjoying your products with the help of images.\r\n\r\n**Features**\r\n* Display Instagram feed on home page or\r\n* Display Instagram feed on category pages or\r\n* Displays Instagram images by hashtag\r\n* Displays Instagram images by keyword\r\n* The store administrator moderates images and can ban certain ones\r\n* Two minutes installation\r\n* Easy localization with the language file\r\n* Free",
    "image":
     {"available_sizes":
       [[[150,
          150],
         "assets/images/resized/0022/7609/227609v2-max-150x150.png"],
        [[250,
          250],
         "assets/images/resized/0022/7609/227609v2-max-250x250.png"],
        [[285,
          285],
         "assets/images/resized/0022/7609/227609v2-max-450x450.png"]],
      "attribution": null}},
   {"name": "Follow Me (Instagram App)",
    "permalink": "follow-me-instagram-app",
    "crunchbase_url": "http://www.crunchbase.com/product/follow-me-instagram-app",
    "homepage_url": "http://app.instagramfollow.me",
    "namespace": "product",
    "overview": "Follow Me enables Instagram users to find Instagram posts based on location instead of hashtags (keywords). Follow Me enables a unique patent pending push-hold gesture in order to search a global map. Follow Me also employs an unique and optional \"auto follow\" feature, which helps Instagram users get more followers.",
    "image":
     {"available_sizes":
       [[[150,
          150],
         "assets/images/resized/0037/3901/373901v2-max-150x150.png"],
        [[250,
          250],
         "assets/images/resized/0037/3901/373901v2-max-250x250.png"],
        [[300,
          300],
         "assets/images/resized/0037/3901/373901v2-max-450x450.png"]],
      "attribution": null}},
   {"name": "Chatworthty for Instagram - iPad edition",
    "permalink": "chatworthty-for-instagram-ipad-edition",
    "crunchbase_url": "http://www.crunchbase.com/product/chatworthty-for-instagram-ipad-edition",
    "homepage_url": null,
    "namespace": "product",
    "overview": null,
    "image": null},
   {"name": "Chatworthy for Instagram - iPhone edition",
    "permalink": "chatworthy-for-instagram-iphone-edition",
    "crunchbase_url": "http://www.crunchbase.com/product/chatworthy-for-instagram-iphone-edition",
    "homepage_url": null,
    "namespace": "product",
    "overview": null,
    "image": null},
   {"name": "Increase Instagram Followers",
    "permalink": "increase-instagram-followers",
    "crunchbase_url": "http://www.crunchbase.com/product/increase-instagram-followers",
    "homepage_url": null,
    "namespace": "product",
    "overview": null,
    "image": null},
   {"name": "How to Gain Instagram Followers",
    "permalink": "how-to-gain-instagram-followers",
    "crunchbase_url": "http://www.crunchbase.com/product/how-to-gain-instagram-followers",
    "homepage_url": null,
    "namespace": "product",
    "overview": null,
    "image": null}]}